#!/bin/bash

symbol=$1
charge=$2

if [ -z "$charge" ]
then
	charge=0
fi

declare -A ATOMIC_SYMBOL_TO_NUMBER

ATOMIC_SYMBOL_TO_NUMBER["H"]=1
ATOMIC_SYMBOL_TO_NUMBER["He"]=2
ATOMIC_SYMBOL_TO_NUMBER["Li"]=3
ATOMIC_SYMBOL_TO_NUMBER["Be"]=4
ATOMIC_SYMBOL_TO_NUMBER["B"]=5
ATOMIC_SYMBOL_TO_NUMBER["C"]=6
ATOMIC_SYMBOL_TO_NUMBER["N"]=7
ATOMIC_SYMBOL_TO_NUMBER["O"]=8
ATOMIC_SYMBOL_TO_NUMBER["F"]=9
ATOMIC_SYMBOL_TO_NUMBER["Ne"]=10
ATOMIC_SYMBOL_TO_NUMBER["Na"]=11
ATOMIC_SYMBOL_TO_NUMBER["Mg"]=12
ATOMIC_SYMBOL_TO_NUMBER["Al"]=13
ATOMIC_SYMBOL_TO_NUMBER["Si"]=14
ATOMIC_SYMBOL_TO_NUMBER["P"]=15
ATOMIC_SYMBOL_TO_NUMBER["S"]=16
ATOMIC_SYMBOL_TO_NUMBER["Cl"]=17
ATOMIC_SYMBOL_TO_NUMBER["Ar"]=18

ATOMIC_SYMBOL_TO_NUMBER["H"]=1
ATOMIC_SYMBOL_TO_NUMBER["HE"]=2
ATOMIC_SYMBOL_TO_NUMBER["LI"]=3
ATOMIC_SYMBOL_TO_NUMBER["BE"]=4
ATOMIC_SYMBOL_TO_NUMBER["B"]=5
ATOMIC_SYMBOL_TO_NUMBER["C"]=6
ATOMIC_SYMBOL_TO_NUMBER["N"]=7
ATOMIC_SYMBOL_TO_NUMBER["O"]=8
ATOMIC_SYMBOL_TO_NUMBER["F"]=9
ATOMIC_SYMBOL_TO_NUMBER["NE"]=10
ATOMIC_SYMBOL_TO_NUMBER["NA"]=11
ATOMIC_SYMBOL_TO_NUMBER["MG"]=12
ATOMIC_SYMBOL_TO_NUMBER["AL"]=13
ATOMIC_SYMBOL_TO_NUMBER["SI"]=14
ATOMIC_SYMBOL_TO_NUMBER["P"]=15
ATOMIC_SYMBOL_TO_NUMBER["S"]=16
ATOMIC_SYMBOL_TO_NUMBER["CL"]=17
ATOMIC_SYMBOL_TO_NUMBER["AR"]=18

declare -A ATOMIC_NAME_TO_NUMBER

ATOMIC_NAME_TO_NUMBER["Hydrogen"]=1 
ATOMIC_NAME_TO_NUMBER["Helium"]=2 
ATOMIC_NAME_TO_NUMBER["Lithium"]=3 
ATOMIC_NAME_TO_NUMBER["Beryllium"]=4 
ATOMIC_NAME_TO_NUMBER["Boron"]=5 
ATOMIC_NAME_TO_NUMBER["Carbon"]=6 
ATOMIC_NAME_TO_NUMBER["Nitrogen"]=7 
ATOMIC_NAME_TO_NUMBER["Oxygen"]=8 
ATOMIC_NAME_TO_NUMBER["Fluorine"]=9 
ATOMIC_NAME_TO_NUMBER["Neon"]=10 
ATOMIC_NAME_TO_NUMBER["Sodium"]=11 
ATOMIC_NAME_TO_NUMBER["Magnesium"]=12 
ATOMIC_NAME_TO_NUMBER["Aluminum"]=13 
ATOMIC_NAME_TO_NUMBER["Silicon"]=14 
ATOMIC_NAME_TO_NUMBER["Phosphorus"]=15 
ATOMIC_NAME_TO_NUMBER["Sulfur"]=16 
ATOMIC_NAME_TO_NUMBER["Chlorine"]=17 
ATOMIC_NAME_TO_NUMBER["Argon"]=18 
ATOMIC_NAME_TO_NUMBER["Potassium"]=19 
ATOMIC_NAME_TO_NUMBER["Calcium"]=20 
ATOMIC_NAME_TO_NUMBER["Scandium"]=21 
ATOMIC_NAME_TO_NUMBER["Titanium"]=22 
ATOMIC_NAME_TO_NUMBER["Vanadium"]=23 
ATOMIC_NAME_TO_NUMBER["Chromium"]=24 
ATOMIC_NAME_TO_NUMBER["Manganese"]=25 
ATOMIC_NAME_TO_NUMBER["Iron"]=26 
ATOMIC_NAME_TO_NUMBER["Cobalt"]=27 
ATOMIC_NAME_TO_NUMBER["Nickel"]=28 
ATOMIC_NAME_TO_NUMBER["Copper"]=29 
ATOMIC_NAME_TO_NUMBER["Zinc"]=30 
ATOMIC_NAME_TO_NUMBER["Gallium"]=31 
ATOMIC_NAME_TO_NUMBER["Germanium"]=32 
ATOMIC_NAME_TO_NUMBER["Arsenic"]=33 
ATOMIC_NAME_TO_NUMBER["Selenium"]=34 
ATOMIC_NAME_TO_NUMBER["Bromine"]=35 
ATOMIC_NAME_TO_NUMBER["Krypton"]=36 
ATOMIC_NAME_TO_NUMBER["Rubidium"]=37 
ATOMIC_NAME_TO_NUMBER["Strontium"]=38 
ATOMIC_NAME_TO_NUMBER["Yttrium"]=39 
ATOMIC_NAME_TO_NUMBER["Zirconium"]=40 
ATOMIC_NAME_TO_NUMBER["Niobium"]=41 
ATOMIC_NAME_TO_NUMBER["Molybdenum"]=42 
ATOMIC_NAME_TO_NUMBER["Technetium"]=43 
ATOMIC_NAME_TO_NUMBER["Ruthenium"]=44 
ATOMIC_NAME_TO_NUMBER["Rhodium"]=45 
ATOMIC_NAME_TO_NUMBER["Palladium"]=46 
ATOMIC_NAME_TO_NUMBER["Silver"]=47 
ATOMIC_NAME_TO_NUMBER["Cadmium"]=48 
ATOMIC_NAME_TO_NUMBER["Indium"]=49 
ATOMIC_NAME_TO_NUMBER["Tin"]=50 
ATOMIC_NAME_TO_NUMBER["Antimony"]=51 
ATOMIC_NAME_TO_NUMBER["Tellurium"]=52 
ATOMIC_NAME_TO_NUMBER["Iodine"]=53 
ATOMIC_NAME_TO_NUMBER["Xenon"]=54 
ATOMIC_NAME_TO_NUMBER["Cesium"]=55 
ATOMIC_NAME_TO_NUMBER["Barium"]=56 
ATOMIC_NAME_TO_NUMBER["Lanthanum"]=57 
ATOMIC_NAME_TO_NUMBER["Cerium"]=58 
ATOMIC_NAME_TO_NUMBER["Praseodymium"]=59 
ATOMIC_NAME_TO_NUMBER["Neodymium"]=60 
ATOMIC_NAME_TO_NUMBER["Promethium"]=61 
ATOMIC_NAME_TO_NUMBER["Samarium"]=62 
ATOMIC_NAME_TO_NUMBER["Europium"]=63 
ATOMIC_NAME_TO_NUMBER["Gadolinium"]=64 
ATOMIC_NAME_TO_NUMBER["Terbium"]=65 
ATOMIC_NAME_TO_NUMBER["Dysprosium"]=66 
ATOMIC_NAME_TO_NUMBER["Holmium"]=67 
ATOMIC_NAME_TO_NUMBER["Erbium"]=68 
ATOMIC_NAME_TO_NUMBER["Thulium"]=69 
ATOMIC_NAME_TO_NUMBER["Ytterbium"]=70 
ATOMIC_NAME_TO_NUMBER["Lutetium"]=71 
ATOMIC_NAME_TO_NUMBER["Hafnium"]=72 
ATOMIC_NAME_TO_NUMBER["Tantalum"]=73 
ATOMIC_NAME_TO_NUMBER["Tungsten"]=74 
ATOMIC_NAME_TO_NUMBER["Rhenium"]=75 
ATOMIC_NAME_TO_NUMBER["Osmium"]=76 
ATOMIC_NAME_TO_NUMBER["Iridium"]=77 
ATOMIC_NAME_TO_NUMBER["Platinum"]=78 
ATOMIC_NAME_TO_NUMBER["Gold"]=79 
ATOMIC_NAME_TO_NUMBER["Mercury"]=80 
ATOMIC_NAME_TO_NUMBER["Thallium"]=81 
ATOMIC_NAME_TO_NUMBER["Lead"]=82 
ATOMIC_NAME_TO_NUMBER["Bismuth"]=83 
ATOMIC_NAME_TO_NUMBER["Polonium"]=84 
ATOMIC_NAME_TO_NUMBER["Astatine"]=85 
ATOMIC_NAME_TO_NUMBER["Radon"]=86 
ATOMIC_NAME_TO_NUMBER["Francium"]=87 
ATOMIC_NAME_TO_NUMBER["Radium"]=88 
ATOMIC_NAME_TO_NUMBER["Actinium"]=89 
ATOMIC_NAME_TO_NUMBER["Thorium"]=90 
ATOMIC_NAME_TO_NUMBER["Protactinium"]=91 
ATOMIC_NAME_TO_NUMBER["Uranium"]=92 
ATOMIC_NAME_TO_NUMBER["Neptunium"]=93 
ATOMIC_NAME_TO_NUMBER["Plutonium"]=94 
ATOMIC_NAME_TO_NUMBER["Americium"]=95 
ATOMIC_NAME_TO_NUMBER["Curium"]=96 
ATOMIC_NAME_TO_NUMBER["Berkelium"]=97 
ATOMIC_NAME_TO_NUMBER["Californium"]=98 
ATOMIC_NAME_TO_NUMBER["Einsteinium"]=99 

declare -A ATOMIC_NUMBER_TO_NAME

ATOMIC_NUMBER_TO_NAME["1"]="Hydrogen"
ATOMIC_NUMBER_TO_NAME["2"]="Helium"
ATOMIC_NUMBER_TO_NAME["3"]="Lithium"
ATOMIC_NUMBER_TO_NAME["4"]="Beryllium"
ATOMIC_NUMBER_TO_NAME["5"]="Boron"
ATOMIC_NUMBER_TO_NAME["6"]="Carbon"
ATOMIC_NUMBER_TO_NAME["7"]="Nitrogen"
ATOMIC_NUMBER_TO_NAME["8"]="Oxygen"
ATOMIC_NUMBER_TO_NAME["9"]="Fluorine"
ATOMIC_NUMBER_TO_NAME["10"]="Neon"
ATOMIC_NUMBER_TO_NAME["11"]="Sodium"
ATOMIC_NUMBER_TO_NAME["12"]="Magnesium"
ATOMIC_NUMBER_TO_NAME["13"]="Aluminum"
ATOMIC_NUMBER_TO_NAME["14"]="Silicon"
ATOMIC_NUMBER_TO_NAME["15"]="Phosphorus"
ATOMIC_NUMBER_TO_NAME["16"]="Sulfur"
ATOMIC_NUMBER_TO_NAME["17"]="Chlorine"
ATOMIC_NUMBER_TO_NAME["18"]="Argon"
ATOMIC_NUMBER_TO_NAME["19"]="Potassium"
ATOMIC_NUMBER_TO_NAME["20"]="Calcium"
ATOMIC_NUMBER_TO_NAME["21"]="Scandium"
ATOMIC_NUMBER_TO_NAME["22"]="Titanium"
ATOMIC_NUMBER_TO_NAME["23"]="Vanadium"
ATOMIC_NUMBER_TO_NAME["24"]="Chromium"
ATOMIC_NUMBER_TO_NAME["25"]="Manganese"
ATOMIC_NUMBER_TO_NAME["26"]="Iron"
ATOMIC_NUMBER_TO_NAME["27"]="Cobalt"
ATOMIC_NUMBER_TO_NAME["28"]="Nickel"
ATOMIC_NUMBER_TO_NAME["29"]="Copper"
ATOMIC_NUMBER_TO_NAME["30"]="Zinc"
ATOMIC_NUMBER_TO_NAME["31"]="Gallium"
ATOMIC_NUMBER_TO_NAME["32"]="Germanium"
ATOMIC_NUMBER_TO_NAME["33"]="Arsenic"
ATOMIC_NUMBER_TO_NAME["34"]="Selenium"
ATOMIC_NUMBER_TO_NAME["35"]="Bromine"
ATOMIC_NUMBER_TO_NAME["36"]="Krypton"
ATOMIC_NUMBER_TO_NAME["37"]="Rubidium"
ATOMIC_NUMBER_TO_NAME["38"]="Strontium"
ATOMIC_NUMBER_TO_NAME["39"]="Yttrium"
ATOMIC_NUMBER_TO_NAME["40"]="Zirconium"
ATOMIC_NUMBER_TO_NAME["41"]="Niobium"
ATOMIC_NUMBER_TO_NAME["42"]="Molybdenum"
ATOMIC_NUMBER_TO_NAME["43"]="Technetium"
ATOMIC_NUMBER_TO_NAME["44"]="Ruthenium"
ATOMIC_NUMBER_TO_NAME["45"]="Rhodium"
ATOMIC_NUMBER_TO_NAME["46"]="Palladium"
ATOMIC_NUMBER_TO_NAME["47"]="Silver"
ATOMIC_NUMBER_TO_NAME["48"]="Cadmium"
ATOMIC_NUMBER_TO_NAME["49"]="Indium"
ATOMIC_NUMBER_TO_NAME["50"]="Tin"
ATOMIC_NUMBER_TO_NAME["51"]="Antimony"
ATOMIC_NUMBER_TO_NAME["52"]="Tellurium"
ATOMIC_NUMBER_TO_NAME["53"]="Iodine"
ATOMIC_NUMBER_TO_NAME["54"]="Xenon"
ATOMIC_NUMBER_TO_NAME["55"]="Cesium"
ATOMIC_NUMBER_TO_NAME["56"]="Barium"
ATOMIC_NUMBER_TO_NAME["57"]="Lanthanum"
ATOMIC_NUMBER_TO_NAME["58"]="Cerium"
ATOMIC_NUMBER_TO_NAME["59"]="Praseodymium"
ATOMIC_NUMBER_TO_NAME["60"]="Neodymium"
ATOMIC_NUMBER_TO_NAME["61"]="Promethium"
ATOMIC_NUMBER_TO_NAME["62"]="Samarium"
ATOMIC_NUMBER_TO_NAME["63"]="Europium"
ATOMIC_NUMBER_TO_NAME["64"]="Gadolinium"
ATOMIC_NUMBER_TO_NAME["65"]="Terbium"
ATOMIC_NUMBER_TO_NAME["66"]="Dysprosium"
ATOMIC_NUMBER_TO_NAME["67"]="Holmium"
ATOMIC_NUMBER_TO_NAME["68"]="Erbium"
ATOMIC_NUMBER_TO_NAME["69"]="Thulium"
ATOMIC_NUMBER_TO_NAME["70"]="Ytterbium"
ATOMIC_NUMBER_TO_NAME["71"]="Lutetium"
ATOMIC_NUMBER_TO_NAME["72"]="Hafnium"
ATOMIC_NUMBER_TO_NAME["73"]="Tantalum"
ATOMIC_NUMBER_TO_NAME["74"]="Tungsten"
ATOMIC_NUMBER_TO_NAME["75"]="Rhenium"
ATOMIC_NUMBER_TO_NAME["76"]="Osmium"
ATOMIC_NUMBER_TO_NAME["77"]="Iridium"
ATOMIC_NUMBER_TO_NAME["78"]="Platinum"
ATOMIC_NUMBER_TO_NAME["79"]="Gold"
ATOMIC_NUMBER_TO_NAME["80"]="Mercury"
ATOMIC_NUMBER_TO_NAME["81"]="Thallium"
ATOMIC_NUMBER_TO_NAME["82"]="Lead"
ATOMIC_NUMBER_TO_NAME["83"]="Bismuth"
ATOMIC_NUMBER_TO_NAME["84"]="Polonium"
ATOMIC_NUMBER_TO_NAME["85"]="Astatine"
ATOMIC_NUMBER_TO_NAME["86"]="Radon"
ATOMIC_NUMBER_TO_NAME["87"]="Francium"
ATOMIC_NUMBER_TO_NAME["88"]="Radium"
ATOMIC_NUMBER_TO_NAME["89"]="Actinium"
ATOMIC_NUMBER_TO_NAME["90"]="Thorium"
ATOMIC_NUMBER_TO_NAME["91"]="Protactinium"
ATOMIC_NUMBER_TO_NAME["92"]="Uranium"
ATOMIC_NUMBER_TO_NAME["93"]="Neptunium"
ATOMIC_NUMBER_TO_NAME["94"]="Plutonium"
ATOMIC_NUMBER_TO_NAME["95"]="Americium"
ATOMIC_NUMBER_TO_NAME["96"]="Curium"
ATOMIC_NUMBER_TO_NAME["97"]="Berkelium"
ATOMIC_NUMBER_TO_NAME["98"]="Californium"
ATOMIC_NUMBER_TO_NAME["99"]="Einsteinium"

name=`echo ${ATOMIC_NUMBER_TO_NAME["${ATOMIC_SYMBOL_TO_NUMBER["$symbol"]}"]} | tr "[:upper:]" "[:lower:]"`

if [ "$charge" -eq "0" ]
then
	targetName=${name}table5_a.htm
elif [ "$charge" -eq "1" ]
then
	targetName=${name}table6_a.htm
else
	echo "### ERROR ### Charge $charge is not available in NIST database"
	exit
fi

wget http://physics.nist.gov/PhysRefData/Handbook/Tables/$targetName &> /dev/null
grep "Sup.*href" $targetName \
	| grep -v "Limit" \
	| sed 's/<i>//g;s/<\/i>//g;s/<Sup>//g;s/<sup>//g;s/<\/sup>//g;s/&#176;//g' \
	| awk 'BEGIN{cm1toeV=0.000123984243863132}{printf "%15s%15s%20.5f\n", $1,$2,$4*cm1toeV}' \
	> .data
	
echo "==================================================="
echo "$name (charge=$charge)"
echo "==================================================="
cat .data
	
~/Develop/scift/utils/energyLevels.sh .data 2,3
	
rm $targetName .data

